/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hakathon;

/**
 *
 * @author florence
 */
public class Story extends javax.swing.JFrame {

    /**
     * Creates new form Story
     */
    public Story() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        weeks1 = new javax.swing.JTextField();
        customer1 = new javax.swing.JTextField();
        bud1 = new javax.swing.JTextField();
        weeks2 = new javax.swing.JTextField();
        customer2 = new javax.swing.JTextField();
        bud2 = new javax.swing.JTextField();
        weeks3 = new javax.swing.JTextField();
        customer3 = new javax.swing.JTextField();
        bud3 = new javax.swing.JTextField();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        d = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(997, 566));
        setMinimumSize(new java.awt.Dimension(997, 566));
        setPreferredSize(new java.awt.Dimension(997, 566));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Project No 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 130, 140, 20);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Project No 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 140, 160, 21);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Project No 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(780, 140, 140, 21);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Weeks Expected");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 180, 110, 18);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Customer Satisfaction");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 260, 160, 20);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Project Budget");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 350, 150, 18);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Weeks Expected");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(370, 190, 130, 18);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Customer Satisfaction");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(370, 270, 142, 18);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Customer Satisfaction");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(780, 270, 142, 18);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Weeks Expected");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(780, 190, 130, 18);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Project Budget");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(370, 350, 97, 18);

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Project Budget");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(780, 350, 140, 18);
        getContentPane().add(weeks1);
        weeks1.setBounds(40, 200, 90, 30);

        customer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer1ActionPerformed(evt);
            }
        });
        getContentPane().add(customer1);
        customer1.setBounds(40, 280, 90, 30);
        getContentPane().add(bud1);
        bud1.setBounds(40, 370, 90, 30);
        getContentPane().add(weeks2);
        weeks2.setBounds(370, 210, 90, 30);
        getContentPane().add(customer2);
        customer2.setBounds(370, 290, 90, 30);
        getContentPane().add(bud2);
        bud2.setBounds(370, 370, 90, 30);
        getContentPane().add(weeks3);
        weeks3.setBounds(780, 210, 80, 30);
        getContentPane().add(customer3);
        customer3.setBounds(780, 290, 80, 30);
        getContentPane().add(bud3);
        bud3.setBounds(780, 370, 80, 30);

        button1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/if_General_Office_38_2530790.png"))); // NOI18N
        button1.setText("CHOOSE No.1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(40, 450, 180, 30);

        button2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/if_General_Office_45_2530814 (1).png"))); // NOI18N
        button2.setText("CHOOSE No.2");
        button2.setToolTipText("");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(370, 450, 180, 29);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/if_General_Office_48_2530806.png"))); // NOI18N
        jButton1.setText("CHOOSE No.3");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 450, 190, 29);

        d.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        d.setForeground(new java.awt.Color(255, 255, 255));
        d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/choose1.jpg"))); // NOI18N
        d.setMaximumSize(new java.awt.Dimension(1500, 750));
        d.setMinimumSize(new java.awt.Dimension(1500, 750));
        d.setPreferredSize(new java.awt.Dimension(1500, 750));
        getContentPane().add(d);
        d.setBounds(0, 0, 1500, 570);

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(790, 140, 34, 14);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ComposeProject cp = new ComposeProject();
        cp.setVisible(true);
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ComposeProject cp = new ComposeProject();
        cp.setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ComposeProject cp = new ComposeProject();
        cp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Story.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Story.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Story.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Story.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Story().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField bud1;
    public static javax.swing.JTextField bud2;
    public static javax.swing.JTextField bud3;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    public static javax.swing.JTextField customer1;
    public static javax.swing.JTextField customer2;
    public static javax.swing.JTextField customer3;
    private javax.swing.JLabel d;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField weeks1;
    public static javax.swing.JTextField weeks2;
    public static javax.swing.JTextField weeks3;
    // End of variables declaration//GEN-END:variables
}
